spring.application.name=transaction-authorizer
# AWS SQS (Localstack) configuration
aws.sqs.queue-url=http://localhost:4566/000000000000/conta-bancaria-criada
aws.sqs.endpoint=http://localhost:4566
aws.region=sa-east-1
