spring.application.name=transaction-authorizer

spring.datasource.url=jdbc:postgresql://localhost:5432/app_db
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.datasource.driverClassName=org.postgresql.Driver

# Flyway migration configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.table=flyway_schema_history
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.flyway.out-of-order=false

# AWS SQS (Localstack) configuration
aws.sqs.queue-url=http://localhost:4566/000000000000/conta-bancaria-criada
aws.sqs.endpoint=http://localhost:4566
aws.region=sa-east-1
